#ifndef KEYWORD
#define KEYWORD(x, y)
#endif
// clang-format off
KEYWORD(and, 3)
KEYWORD(break, 5)
KEYWORD(catch, 5)
KEYWORD(class, 5)
KEYWORD(do, 2)
KEYWORD(else, 4)
KEYWORD(false, 5)
KEYWORD(fn, 2)
KEYWORD(for, 3)
KEYWORD(get, 3)
KEYWORD(if, 2)
KEYWORD(import, 6)
KEYWORD(native, 6)
KEYWORD(new, 3)
KEYWORD(nil, 3)
KEYWORD(op, 2)
KEYWORD(or, 2)
KEYWORD(print, 5)
KEYWORD(priv, 4)
KEYWORD(pub, 3)
KEYWORD(ret, 3)
KEYWORD(set, 3)
KEYWORD(static, 6)
//KEYWORD(this, 4)
KEYWORD(throw, 5)
KEYWORD(true, 4)
KEYWORD(try, 3)
KEYWORD(while, 5)
// clang-format on
