#ifndef SCONSTANT
#define SCONSTANT(name, s)
#endif
#ifndef SYMCONSTANT
#define SYMCONSTANT(name)
#endif

SCONSTANT(EmptyString, "")
SCONSTANT(RuntimeException, "RuntimeException")
SCONSTANT(any_, "any")
SCONSTANT(error, "error")
SCONSTANT(Number, "Number")
SCONSTANT(array_, "array")
SCONSTANT(hashmap, "hashmap")
SCONSTANT(range, "range")
SCONSTANT(Nil, "Nil")
SCONSTANT(repl, "repl")
SCONSTANT(true_, "true")
SCONSTANT(false_, "false")
SCONSTANT(GcObject, "GcObject")
SCONSTANT(Boolean, "Boolean")
SCONSTANT(str, "str")
SCONSTANT(nil, "nil")
SCONSTANT(i64, "i64")
SCONSTANT(f64, "f64")
SCONSTANT(i1, "i1")
#define TYPE(r, n) SCONSTANT(type_##n, #n)
#include "valuetypes.h"

#define MODULE(x, y) SCONSTANT(x, #x)
#include "modules.h"

SCONSTANT(sym_dot, ".")
SCONSTANT(sig_array_1, "array(_)")
SCONSTANT(sig_hashmap_0, "hashmap()")
SCONSTANT(sig_constructor_0, "()")
SCONSTANT(sig_add, "+(_)")
SCONSTANT(sig_sub, "-(_)")
SCONSTANT(sig_mul, "*(_)")
SCONSTANT(sig_div, "/(_)")
SCONSTANT(sig_eq, "==(_)")
SCONSTANT(sig_neq, "!=(_)")
SCONSTANT(sig_less, "<(_)")
SCONSTANT(sig_lesseq, "<=(_)")
SCONSTANT(sig_greater, ">(_)")
SCONSTANT(sig_greatereq, ">=(_)")
SCONSTANT(sig_band, "&(_)")
SCONSTANT(sig_bor, "|(_)")
SCONSTANT(sig_bnot, "~()")
SCONSTANT(sig_bxor, "^(_)")
SCONSTANT(sig_blshift, "<<(_)")
SCONSTANT(sig_brshift, ">>(_)")
SCONSTANT(sig_subscript_get, "[](_)")
SCONSTANT(sig_subscript_set, "[](_,_)")
SCONSTANT(sig_neg, "-()")
SCONSTANT(sig_incr, "++(_)")
SCONSTANT(sig_decr, "--(_)")
SCONSTANT(sig_hash, "hash()")
SCONSTANT(sig_str, "str()")
SCONSTANT(sig_str1, "str(_)")
SCONSTANT(sig_fmt, "fmt(_)")
SCONSTANT(sig_fmt2, "fmt(_,_)")
SCONSTANT(sig_derive, " derive(_)")
SCONSTANT(sig_next, "next()")
SCONSTANT(field_has_next, "has_next")
SCONSTANT(undefined, "<undefined>")

SYMCONSTANT(sig_add)
SYMCONSTANT(sig_sub)
SYMCONSTANT(sig_mul)
SYMCONSTANT(sig_div)
SYMCONSTANT(sig_eq)
SYMCONSTANT(sig_neq)
SYMCONSTANT(sig_less)
SYMCONSTANT(sig_lesseq)
SYMCONSTANT(sig_greater)
SYMCONSTANT(sig_greatereq)
SYMCONSTANT(sig_band)
SYMCONSTANT(sig_bor)
SYMCONSTANT(sig_bnot)
SYMCONSTANT(sig_bxor)
SYMCONSTANT(sig_blshift)
SYMCONSTANT(sig_brshift)
SYMCONSTANT(sig_subscript_get)
SYMCONSTANT(sig_subscript_set)
SYMCONSTANT(sig_incr)
SYMCONSTANT(sig_decr)
SYMCONSTANT(sig_neg)
SYMCONSTANT(sig_constructor_0)
SYMCONSTANT(str)
SYMCONSTANT(sig_hash)
SYMCONSTANT(sig_str)
SYMCONSTANT(sig_str1)
SYMCONSTANT(sig_fmt)
SYMCONSTANT(sig_fmt2)
SYMCONSTANT(sig_derive)
SYMCONSTANT(field_has_next)
SYMCONSTANT(sig_next)
#undef SCONSTANT
#undef SYMCONSTANT
