#!/usr/bin/env python

import sys

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Error: Invalid number of arguments!")
        sys.exit(1)
    ifile = sys.argv[1]
    ofile = sys.argv[2]
    with open(ofile, "w") as o:
        o.write("// autogenerated from core.n\n// do not edit\n")
        o.write("const char* core_source = ")
        with open(ifile, "r") as i:
            for line in i.readlines():
                line = line.replace("\"", "\\\"")[:-1]
                o.write("\"" + line + "\\n\"\n")
        o.write(";")
