name: Linux (GcStress) 

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-12, clang++]
        cxxstd: [c++11, c++14, c++17, c++20]
      fail-fast: false

    steps:
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0.4"
    - uses: actions/checkout@v2
    - name: ${{ matrix.compiler }} ${{ matrix.cxxstd }}
      env:
        CXX: ${{ matrix.compiler }}
        CXXSTD: ${{ matrix.cxxstd }}
      run: eval "${CXX}" -v && echo "${CXXSTD}" && make clean && make gc_stress CXXSTD="${CXXSTD}" -j && ./next tests/benchmark_orchestrator_gc.n
