name: Linux Build (GcStress) 

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Running GC Stress Benchmarks
      env:
        CXX: ${{ matrix.compiler }}
      run: eval "${CXX}" -v && make clean && make debug_gc_stress -j && ./next tests/benchmark_orchestrator_gc.n
