name: Windows Build

on: push

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Release, Debug, DebugGc, DebugGcStress]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: ${{ matrix.config }}
      env:
        CONFIG: ${{ matrix.config }}
      run: msbuild /p:Configuration=!CONFIG! /p:OutDir=. && set next=Next.exe && next tests\\orchestrator.n && python utils\\benchmark.py -n 10
