name: Windows Build (GcStress)

on: push

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0.4"
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: Running GC Stress Benchmarks
      run: msbuild /p:Configuration=GcStress /p:OutDir=. && .\\Next.exe tests\\benchmark_orchestrator_gc.n
