name: Windows Build

on: push

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Release, Debug]
      fail-fast: false
    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16.0.4"
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: ${{ matrix.config }}
      env:
        CONFIG: ${{ matrix.config }}
      run: msbuild /p:Configuration=$env:CONFIG /p:OutDir=. && set next=Next.exe && .\\Next.exe tests\\orchestrator.n && python util\\benchmark.py -n 10 -l next
